Add goToUrl action creator
ngrx/router-store pull request #36
Opened 2017-01-10 15:32 UTC by mischkl

Fixes #30

2017-01-15 21:58 UTC, brandonroberts requested changes

2017-01-15 21:58 UTC, brandonroberts commented on src/actions.ts
> +  GO_TO_URL: '[Router] Go to URL',
Change the action to `URL` instead

2017-01-15 21:58 UTC, brandonroberts commented on src/actions.ts
> +export function goToUrl(path: string, extras?: NavigationExtras): Action {
Change the function name to `url`

2017-01-15 21:58 UTC, brandonroberts commented on src/connect.ts
> +          if (typeof path === 'string') {
The action is already typed to a `string` so no need to validate it here.

2017-03-15 01:14 UTC, closed without merging

2017-05-29 09:16 UTC, mischkl commented
Hello, may I ask why this was closed? Is this feature going to be implemented still?

2017-07-02 11:46 UTC, jinder commented
@mischkl I think because they're concentrating on NGRX 4, which will use the normal router methods not dispatchable actions.